source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in auth.gemspec.
gemspec

gem "pg"

gem "sprockets-rails"

# Start debugger with binding.b [https://github.com/ruby/debug]
# gem "debug", ">= 1.0.0"
gem "ahoy_matey"
# gem "devise"
gem "dotenv-rails"
gem "geocoder"
gem "pagy"

group :development do
  gem "dalli"
  gem "memory_profiler"
  gem "sorbet"
  gem "sorbet-runtime"
  gem "tapioca", require: false
end

group :development, :test do
  gem "factory_bot_rails"
  gem "rspec-expectations"
  gem "rspec-rails"
end

group :rubocop do
  gem "rubocop-packaging"
  gem "rubocop-performance"
  gem "rubocop-rails"
  gem "rubocop-rspec"
  gem "rubocop-shopify"
end
